### ISSUE TITLE
Create database 

### ISSUE THREAD

**Issue by StavniczkiBalazs** [JaksyMarci/Cherry-Blossom-Diner#1]
create an sqlite database for the CBD project

**Comment by JaksyMarci** [comment]
My proposed structure
![image](https://user-images.githubusercontent.com/70854029/194523540-1f1d615f-5a14-4726-8f13-36d0161ea7dc.png)

**Comment by StavniczkiBalazs** [comment]
I've created the frame of the DB with the help of php artisan. I'll commit the migrations files. run 'php artisan migrate' to generate the tables for your DB.

**Comment by JaksyMarci** [comment]
I've checked the database structure and it seems good, only needs to be seeded now.

**Comment by StavniczkiBalazs** [comment]
I merged the seeders and the factories to main from FeatureBranch 1. It is ready to use
